# -*- coding: utf-8 -*-
"""model_inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KCHfAGyKHdrTJMXPPJZA912IVLHH1ZC_
"""

import joblib
import numpy as np

model = joblib.load("career_model.joblib")

career_map = {
    0: "Data Analyst",
    1: "Business Analyst",
    2: "Product Analyst"
}

def predict_career(python, sql, ml, design, comm, cgpa, projects):
    X = np.array([[python, sql, ml, design, comm, cgpa, projects]])
    probs = model.predict_proba(X)[0]
    classes = model.classes_

    results = sorted(zip(classes, probs), key=lambda x: x[1], reverse=True)
    for c, p in results:
        print(f"{career_map[int(c)]} – {p * 100:.2f}% match")

if __name__ == "__main__":
    # Example: Rahul's profile
    print("Career recommendations for Rahul:\n")
    predict_career(
        python=60,
        sql=70,
        ml=55,
        design=40,
        comm=80,
        cgpa=8.0,
        projects=3
    )