# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PnIrTbK7uMge8LpgsEMwUouU269xOy7G
"""

from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import numpy as np

app = FastAPI(title="Career Recommendation API")

model = joblib.load("career_model.joblib")

career_map = {
    0: "Data Analyst",
    1: "Business Analyst",
    2: "Product Analyst"
}

class ProfileInput(BaseModel):
    python: int
    sql: int
    ml: int
    design: int
    comm: int
    cgpa: float
    projects: int

@app.post("/predict")
def predict_career(profile: ProfileInput):
    X = np.array([[profile.python, profile.sql, profile.ml,
                   profile.design, profile.comm, profile.cgpa,
                   profile.projects]])
    probs = model.predict_proba(X)[0]
    classes = model.classes_

    results = sorted(zip(classes, probs), key=lambda x: x[1], reverse=True)
    output = [
        {
            "career_id": int(c),
            "career_name": career_map[int(c)],
            "score": round(float(p) * 100, 2)
        }
        for c, p in results
    ]
    return {"recommendations": output}

@app.get("/health")
def health():
    return {"status": "ok"}